### ISSUE TITLE
upgrade pip/setuptools and install wheel in venv?

### ISSUE THREAD

**Issue by anthrotype** [rpkilby/tox-venv#17]
when using the regular tox (without tox-venv plugin), the created environments will have the latest versions of pip and setuptools, because the default behaviour of virtualenv is to reach out to the Internet to download the latest versions from PyPI, unless --no-download is passed (which [tox doesn't seem to be doing](https://github.com/tox-dev/tox/blob/cb2dff12b9dae52b64fea6514461b3155ecc43a0/tox/venv.py#L452-L466)). In addition, virtualenv always installs the wheel module as well as pip and setuptools.

However, when using the built-in python3's `venv` module, pip and setuptools gets installed using the `ensurepip` built-in module, which by design [does not access the Internet](https://docs.python.org/3/library/ensurepip.html). Also, wheel doesn't get automatically installed when doing ensurepip.

For consistency between the tox environments for python2.7 and those for python3+, it would be great if tox-venv plugin would do a `python -m pip install --upgrade pip setuptools wheel` after having created the new venv.

Thanks!

**Comment by rpkilby** [comment]
Yeah - this shouldn't be difficult to add. Possible ini setup...

```ini
[tox]
...

[venv]
upgrade = true  ; upgrades pip & setuptools
upgrade =  ; or upgrade pip & setuptools to the specified versions
    pip>=10
    setuptools>=36
```

That said, I would say 👎 to including `wheel` here. The only *necessary* dependencies for installing packages are `pip` and `setuptools`. If tests rely on `wheel`, they should depend on it explicitly.

**Comment by anthrotype** [comment]
Thanks @rpkilby. The proposed config option looks good to me. And I'm fine with depending explicitly on wheel when needed.
I'm afraid I won't have time to work on a PR right now, but I'll keep an eye on it.

**Comment by AvdN** [comment]
I was going to ask if something like this could be added. The other thing I was going to look at is run something in the configuration (possible in my tox-globinterpreter install) before the normal install. 
Since I gernate my tox.ini files on the fly, adding a `pip upgrade` line is not a big hassle (but neither is adding a `[venv]` section :-)

If that option `upgrade=true` is set though, it would be faster to create the `venv` with `--without-pip` and then use the pip belonging to the python installed to directly install the latest version of pip in the newly created virtual environment with something like:

```
 /opt/python/version/bin/pip --disable-pip-version-check --target .tox/pyXY pip
```
(Actually --target puts everything, including the executable `pip` under `lib/pythonX.Y/site-packages) and ``--root` and `--prefix` don't seem to do much. So you would need an ``--install-option`` (I should have known: https://stackoverflow.com/a/11017307/1307905 )

**Comment by AvdN** [comment]
FWIW: I solved this for me by writing a utility that downloads the latest wheels for pip and setuptools and updates the hardcoded numbers in ``lib/ensurepip/__init__.py``
You only need only one  [file](https://bitbucket.org/ruamel/upgrade_ensurepip/src/default/upgrade_ensurepip.py), which can be found as package on ``https://pypi.org/project/upgrade-ensurepip/``

**Comment by jaraco** [comment]
#25 also addresses this issue.

**Comment by rpkilby** [comment]
Is this effectively resolved by the `requires` setting? 
https://tox.readthedocs.io/en/latest/config.html#tox-global-settings

<blockquote><div><strong><a href="https://tox.readthedocs.io/en/latest/config.html#tox-global-settings">tox configuration specification — tox 3.9.1.dev1 documentation</a></strong></div></blockquote>

**Comment by jaraco** [comment]
I don’t think so. The requires directive indicates which version of tox-venv should be used... or which version of setuptools must be present in the environment alongside tox. But it doesn’t designate anything about the target environments.

**Comment by rpkilby** [comment]
👌 Thanks

**Comment by jaraco** [comment]
It sounds like the solution is to use `tox-pip-version` with `pip-version=pip`. In other words:

```
[tox]
minversion = 3.2
requires =
    tox-pip-version

[testenv]
pip_version = pip
```

**Comment by jaraco** [comment]
This problem becomes more serious in light of tox-dev/tox-venv#42. Now tox-venv is simply unviable in some environments where tox without it works. And the `tox-pip-version` recommendation is no help.

**Comment by jaraco** [comment]
tox-venv is being deprecated, so this issue no longer needs attention.
