### ISSUE TITLE
Thank you! (Not an issue)

### ISSUE THREAD

**Issue by obestwalter** [rpkilby/tox-venv#20]
Hi, I just wanted to let you know, that your plugin safed us unnecessary trouble today. We have some old test servers chugging along on Python 3.4 and all of a sudden tox got stuck in the create stage somewhere in the depth of virtualenv. After some fruitless investigation, we decided to use venv instead, typed `pip install tox-venv`, problem solved :)

**Comment by rpkilby** [comment]
I'm just glad that other people are finding this useful. 😄
