### ISSUE TITLE
running tests with current tox 3.1.2 show failures

### ISSUE THREAD

**Issue by anthrotype** [rpkilby/tox-venv#22]
Running the tests for tox-venv fails when the latest available tox from PyPI (3.1.2) is installed.
The setup.py `install_requires` only has a minimum version specifier `tox>=2.0`, maybe it should also have a upper bound.
In any case, the updated tests from upstream tox repository should be copied over here.
@rpkilby do you have an automated way to do this, or you just copy/paste and commit?

**Comment by rpkilby** [comment]
Unfortunately, it's just copy+paste+rebase changes. 

Is tox-venv currently failing against tox 3.1?

**Comment by rpkilby** [comment]
Ah, I just noticed #23. Unfortunately, I need to update the tests on a version-by-version basis.

**Comment by rpkilby** [comment]
This should be fixed.
- The test suite is already ran by the current version of tox on PyPI
- Internally, the test suite is tested against tox 3.8.1
