### ISSUE TITLE
Broken on macOS with Python 3.6 and below

### ISSUE THREAD

**Issue by jaraco** [rpkilby/tox-venv#24]
On Python 3.4 and 3.5 on macOS (at least), venv is no longer viable and pip is broken:

```
draft $ .env/bin/python -m pip install -U pip
Cache entry deserialization failed, entry ignored
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) - skipping
Requirement already up-to-date: pip in ./.env/lib/python3.5/site-packages
```

As a result, this means that `tox-venv` also is broken on those Pythons.

The only solution I've found is to use an external tool like cUrl or httpie to download and install a newer pip (9.0.3 or later and maybe 10 is required, IIUC).

**Comment by jaraco** [comment]
Upstream issue is pypa/pip#5236; the only recommended solution is to use a system tool (curl) to upgrade pip. Probably tox-venv should bundle a later pip and install it after building the env.

**Comment by gaborbernat** [comment]
there's a plan we're incorporate this plugin into core tox with next version. I would probably avoid bundle pip, but instead download it on demand. The plan is that users should be able to specify pip, setuptools and wheel after venv creation.will keep this situation in mind, thanks for raising it.

**Comment by jaraco** [comment]
> instead download it on demand

I've found it's difficult to do this securely and in a cross-platform way. Setuptools used to have an ez_setup.py script that would do this by shelling out to powershell or curl or wget as available or fall back to an insecure urllib.request handler. I think that's why `ensure-pip` and `virtualenv` bundle `pip` (and for bootstrapping reasons, setuptools).

Not that it can't be done - just beware there are dragons.

**Comment by rpkilby** [comment]
Does `virtualenv` actually bundle `pip`? I thought it was downloaded?

**Comment by jaraco** [comment]
[ref](https://github.com/pypa/virtualenv/tree/master/virtualenv_support)

**Comment by jaraco** [comment]
Actually - since virtualenv is already a dependency of tox, perhaps tox-venv (or the merged version) could just install the bundled versions of those packages as found in virtualenv. Then, the behavior between virtualenv and venv would be aligned also.

**Comment by rpkilby** [comment]
On second thought, depending on `virtualenv` may not be a good solution. Once Python 2 is deprecated, `tox` no longer needs to depend on `virtualenv` either. Maybe we should bundle pip?

**Comment by jaraco** [comment]
Whatever it is will probably need to have similar behaviors to what virtualenv does today, including bundling pip and setuptools and wheel. I'll bet pip will be reluctant to bundle pip ;). Perhaps better would be to extract a utility library, something that has these bundled versions and the logic to install them that would run independent of virtualenv... and then virtualenv could depend on or otherwise embed that functionality.

**Comment by jaraco** [comment]
I don't think this is going to be addressed. The proposed solution to use tox-pip-version probably doesn't help here.

**Comment by rpkilby** [comment]
Apologies again for the lack of responsiveness. I'm just going to hold off until tox 4 is released.
