### ISSUE TITLE
Setup appveyor project under the tox-dev org

### ISSUE THREAD

**Issue by rpkilby** [rpkilby/tox-venv#3]
From appveyor's perspective, I do not have sufficient privileges to setup tox-venv under the tox-dev organization. I assume setting up appveyor would require someone with ownership or administrative privileges. @obestwalter and @RonnyPfannschmidt - if either of you could set this up, I'd appreciate it.

**Comment by obestwalter** [comment]
Hi @rpkilby IIRC I don't have admin rights on appveyor as @RonnyPfannschmidt had to hack something with his own account to get it to work. The appveyor builds There is definitely room for improvement regarding how we orgianize our CI setup.

**Comment by obestwalter** [comment]
Just had another look and I have a lot of buttons next to the tox project. But I don't even know that if we have a tox-dev org in appveyor. Can you coach me through this? If you can tell me how I would have to set that up, I would have a go.

**Comment by obestwalter** [comment]
Seems like you don't need anything specific to the organization as @ryanhiebert recently did this for tox-travis here https://github.com/tox-dev/tox-travis/pull/99

**Comment by ryanhiebert** [comment]
I can't guarantee anything about my permission being sufficient in general, because the Travis setup for tox-travis was moved, with assistance at Travis, from my own personal repository.

Edit: Uh, yeah, this was obviously all talking about AppVeyor, sorry, I got confused. 😢

**Comment by obestwalter** [comment]
@ryanhiebert would you be able to give a hand to @rpkilby getting this running on appveyor?

**Comment by gaborbernat** [comment]
@obestwalter related to this: 
@ryanhiebert set up AppVeyor under his personal account, see https://ci.appveyor.com/project/ryanhiebert/tox-travis
that being said tox itself currently uses mine https://ci.appveyor.com/project/gaborbernat/tox
would be nice if we could have under the project itself, e.g. https://ci.appveyor.com/project/tox-dev/tox but I too lack that admin rights :smiley:

**Comment by obestwalter** [comment]
@RonnyPfannschmidt set this up last year, so maybe he can chip in.

**Comment by rpkilby** [comment]
@obestwalter I haven't used Appveyor before, so I can't really provide guidance on how to set this up, or how organizational privileges work. 

For now, I can just set up Appveyor under my account.

**Comment by gaborbernat** [comment]
@obestwalter he set it up to his personal accounts; I've just swapped from his to mine as I wanted rolling builds. We should set up under our own organization though, not someones personal account.  It seems ``pytest`` uses the role account [pytestbot](https://github.com/pytestbot) for AppVeyor.

See https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization for details on how to setup organization level; we could just use a Gmail role account for this maybe?

**Comment by rpkilby** [comment]
Alright, appveyor is setup. For now, I'm not going to worry about having this running under the tox-dev org.
