### ISSUE TITLE
don't use subprocess, prefer action.popen instead 

### ISSUE THREAD

**Issue by gaborbernat** [rpkilby/tox-venv#37]
https://github.com/tox-dev/tox-venv/blob/master/src/tox_venv/hooks.py#L39 instead use ``action.popen`` - subprocesses bypasses both our logging/reporting stack and makes your queries not show up in the ``--result-json``.

**Comment by rpkilby** [comment]
So I was thinking about this the other day - my thoughts were twofold:

- Using `action.popen` doesn't seem like it would be beneficial. We're testing the Python version as a sanity check and using `real_prefix` to test if we're in a virtualenv. This doesn't seem like the kind of output that needs to be captured/reported. Output capturing would make more sense if the subprocess was performing some action (e.g., actually creating the venv), right?
- Also, tox is generally undergoing a lot of development. If the internal API isn't stable, then we probably want to rely on those internals as little as possible, right? i.e., `venv.session` was removed, actions were recently refactored, will its API also change?

**Comment by gaborbernat** [comment]
@rpkilby it's more of a case of having an easy to debug trace of all commands (so ease of debug-ability in case of failure); which is just as true if the commands are creating some advanced output or just requesting some basic info. If during those checks an exception is raised this would allow end users quickly identify what's the issue, rather now when the output is suppressed. I would also prefer to throw some tox error rather then assert 🤔 asserting seems kinda awkward; we do plan to finalize our API with ``4.0``, not long now and I have no plans to change the API for action.popen

**Comment by rpkilby** [comment]
>  it's more of a case of having an easy to debug trace of all commands

👍 

> I would also prefer to throw some tox error rather then assert 🤔 asserting seems kinda awkward

The version assert is there as a sanity check. Basically, ensure that the venv python is the same version as the venv's underlying python interpreter. This should always pass. If it fails, something has gone horribly wrong, or there is a bug in the plugin. It's not something that would be misconfigured by a user.

That said, it would make sense to raise an exception for the path assert check, since it's not completely unexpected that a user might run into this. Maybe `tox.exception. InterpreterNotFound`? 

> we do plan to finalize our API with 4.0, not long now and I have no plans to change the API for action.popen

Sounds good. I'll go ahead and use `action.popen` then.

**Comment by gaborbernat** [comment]
Yeah 👍 InterpreterNotFound sounds good 👍

**Comment by rpkilby** [comment]
TODO:
- [ ] `subprocess` => `action.popen`
- [ ] raise exception for missing interpreter
- [ ] use the `redirect` argument per #30
