### ISSUE TITLE
Plans for project

### ISSUE THREAD

**Issue by gaborbernat** [rpkilby/tox-venv#47]
Considering virtualenv now creates venv environments, should we deprecate and freeze this project?

**Comment by gaborbernat** [comment]
Note that one can set an env var to convince virtualenv to delegate the job to venv itself 🤷‍♂️

**Comment by rpkilby** [comment]
Yes, tox-venv should be archived as it no longer serves any real purpose. The original goal was to bypass virtualenv and its various bugs, but virtualenv is now well maintained and tox-venv has in turn become its own source of bugs.

For users that want to delegate to `venv`, they just need to add the following, right?

```ini
[testenv]
setenv =
    VIRTUALENV_CREATOR=venv
```

**Comment by gaborbernat** [comment]
Indeed, though virtualenv now creates the same type of virtual environment as venv... so there's no reason why can't just use virtualenv as is.

**Comment by gaborbernat** [comment]
IMHO just archive the project; update README to say the above.
