### ISSUE TITLE
venv results in older Setuptools

### ISSUE THREAD

**Issue by jaraco** [rpkilby/tox-venv#5]
By installing tox-venv, I've started getting bugs in my tests (namely pypa/setuptools#885) because an older Setuptools is installed by venv than is installed by virtualenv (28.8.0 vs. latest).

I'm reporting this behavior here so it can be considered, as I know this library is being considered for default inclusion in tox, so this change will have unintended side effects for users.

I've found if I include `setuptools >= 31.0.1` in my `deps`, it will roughly restore the behavior I was seeing before.

**Comment by rpkilby** [comment]
Interesting. Thinking about this... is there a reason `setuptools` *should* be included here? It really isn't necessary from tox/tox-venv's perspective. My guess is that it's more of a historical ism of virtualenv?

> I'm reporting this behavior here so it can be considered, as I know this library is being considered for default inclusion in tox, so this change will have unintended side effects for users.

This most likely won't happen in the near future. For now, tox supports python 3.3 test environments, which would prevent the original PR from being merged, as 3.3 venv was missing certain features. My guess is that tox-venv will be reevaluated once python 2 EOL's, rendering virtualenv unneeded as a dependency.

**Comment by gaborbernat** [comment]
@jaraco your tests/project relies on ``setuptools >= 31.0.1``, your project should express this dependency and probably tox should install it before it invokes subsequent commands (e.g. test).  This too falls under the umbrella of PEP-518. The next iteration of tox (v3) will solve this issue: https://tox3.readthedocs.io/en/latest/ . In the meantime adding that requirement into deps will do the trick.

**Comment by rpkilby** [comment]
I'm going to close this. It sounds like tox will address this in v3, and in general, it sounds like adding `setuptools` to the dependencies is the correct thing to do.

**Comment by jaraco** [comment]
And indeed, that's what I've done - https://github.com/jaraco/skeleton/commit/99d850f0ed9852993626d4869e9f096e1643be6d
