### ISSUE TITLE
How is this package to be used?

### ISSUE THREAD

**Issue by icemac** [rpkilby/tox-venv#8]
The purpose of this package sounds interesting, but how is it to be used?
Has it to be installed in the same virtualenv as `tox`?
Has it to be configured in `tox.ini`?

Sorry for not knowing this and not finding the appropriate documentation.

**Comment by rpkilby** [comment]
Thanks for pointing this out - an obvious oversight in the readme. 

All you need to do is install tox and tox-venv, then run `tox` as normal. There is no configuration. That said, you will need to clear out your `.tox` directory, as environments are not automatically recreated. 

```bash
$ pip install tox tox-venv
$ tox
```

**Comment by icemac** [comment]
Thank you for your explanation.
